/* This file should be auto-generated by tool, please don't manully modify it.*/
#include "hisi_battery_data_default.c"
#include "hisi_battery_data_sony_2000.c"

static struct hisi_smartstar_coul_battery_data *battery_data_array[] = {
    &default_battery_data,
    &sony_2000_battery_data,
};



