#
# Makefile for sensor chip drivers.
#
obj-$(CONFIG_K3V2_CPU_TEMP_SENSOR)	+= k3v2_temp_sensor.o
obj-$(CONFIG_K3V2_AP_SENSOR)	+= ap_temp_sensor.o
obj-$(CONFIG_K3V2_SIM_SENSOR)	+= sim_temp_sensor.o


obj-$(CONFIG_K3V2_TEMP_GOVERNOR)	+= k3v2_temperature.o
