/*Copyright Huawei Technologies Co., Ltd. 1998-2011. All rights reserved. 
 *This file is Auto Generated */


#ifndef _CONFIG_BOARDID_H
#define _CONFIG_BOARDID_H


#define BOARD_ID_OSCAR_CG_VB 732
#define BOARD_ID_OSCAR_CG_VC 734
#define BOARD_ID_BALONG_LPDDR2_UDP_OSCAR_RF 9
#define BOARD_ID_OSCAR_TL_VA 715
#define BOARD_ID_SOPHIA_ULG_VD 833
#define BOARD_ID_SOPHIA_UL_VY 810
#define BOARD_ID_BALONG_LPDDR2_UDP 0
#define BOARD_ID_BALONG_LPDDR3_UDP_DCM_RF 41
#define BOARD_ID_SOPHIA_UL_VC 802
#define BOARD_ID_SOPHIA_UL_VD 803
#define BOARD_ID_OSCAR_VUL_VD 772
#define BOARD_ID_OSCAR_4G_VD 771
#define BOARD_ID_EDGE_PLUS_UL_VX 758
#define BOARD_ID_BALONG_DDR3CAP_UDP_6361S 12
#define BOARD_ID_OSCAR_4G_VC 761
#define BOARD_ID_BALONG_DDR3CAP_UDP 10
#define BOARD_ID_BALONG_DDR3CAP_UDP_FHD 97
#define BOARD_ID_OSCAR_VTL_VD 774
#define BOARD_ID_SOPHIA_TL_VB 821
#define BOARD_ID_SOPHIA_TL_VC 822
#define BOARD_ID_OSCAR_TL_VB 770
#define BOARD_ID_OSCAR_CG_VD 735
#define BOARD_ID_SOPHIA_ULG_HVA 835
#define BOARD_ID_SOPHIA_ULG_VC 832
#define BOARD_ID_EDGE_PLUS_UL_VA 701
#define BOARD_ID_EDGE_PLUS_UL_VZ 790
#define BOARD_ID_SOPHIA_ULG_VB 831
#define BOARD_ID_OSCAR_CG_VA 712
#define BOARD_ID_BALONG_LPDDR2_UDP_DCM_RF 1
#define BOARD_ID_SOPHIA_UL_VU 860
#define BOARD_ID_OSCAR_VTL_VE 784
#define BOARD_ID_OSCAR_4G_VE 781
#define BOARD_ID_OSCAR_VUL_VE 782
#define BOARD_ID_BALONG_MHLCAP_UDP_FHD 96
#define BOARD_ID_SOPHIA_TL_VA 820
#define BOARD_ID_SOPHIA_UL_VB 801
#define BOARD_ID_SOPHIA_UL_VA 800
#define BOARD_ID_SOPHIA_ULG_VA 830
#define BOARD_ID_EDGE_PLUS_UL_VB 750
#define BOARD_ID_SOPHIA_TL_VD 823
#define BOARD_ID_SOPHIA_CLG_VB 841
#define BOARD_ID_EDGE_PLUS_UL_VY 759
#define BOARD_ID_BALONG_LPDDR3_UDP 40
#define BOARD_ID_BALONG_LPDDR2_UDP_6361S 2
#define BOARD_ID_OSCAR_UL_VB 760
#define BOARD_ID_BALONG_MHLCAP_UDP 20
#define BOARD_ID_BALONG_DDR3CAP_UDP_DCM_RF 11
#define BOARD_ID_BALONG_LPDDR3_UDP_6361S 42
#define BOARD_ID_BALONG_MHL_UDP 30
#define BOARD_ID_SOPHIA_CLG_VA 840
#define BOARD_ID_OSCAR_UL_VA 716
#endif
