EXTRA_CFLAGS = -Idrivers/video/hi6620

obj-$(CONFIG_LCD_SAMSUNG_LMS350DF04) += ldi_samsung_LMS350DF04.o

obj-$(CONFIG_LCD_TOSHIBA_MDW70) += mipi_toshiba_MDW70_V001.o

obj-$(CONFIG_LCD_JDI_OTM1282B) += mipi_jdi_OTM1282B.o

obj-$(CONFIG_LCD_CMI_OTM1282B) += mipi_cmi_OTM1282B.o

obj-$(CONFIG_LCD_JDI_OTM1902B) += mipi_jdi_OTM1902B.o

obj-$(CONFIG_TPS65132) += tps65132.o

obj-$(CONFIG_LCD_TOSHIBA_MDY90) += mipi_toshiba_MDY90.o
