obj-y				:= drv_abb.o drv_audio.o drv_usb.o drv_debug_led.o\
drv_mntn.o drv_hkadc.o drv_ipcm.o drv_version.o\
drv_dpm.o drv_nv.o drv_modem_bsp.o drv_sd.o\
drv_sec.o drv_pmu.o drv_sci.o drv_wifi.o\
drv_socp.o drv_sysctrl.o drv_timer.o drv_update.o\
drv_wdt.o drv_gpio.o drv_charge.o drv_mem_remap.o\
drv_oled.o drv_ifc.o drv_edma.o