##############################################
#     Make file of OV5642 camera sensor
##############################################

EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HI6620_CAMERA_OV5648_FOXCONN) += ov5648_foxconn.o

#################### END #####################
