EXTRA_CFLAGS += -Idrivers/mailbox/
EXTRA_CFLAGS += -I../vendor/hisi/include/drv/MODULE_H
EXTRA_CFLAGS += -I../vendor/hisi/include/med
EXTRA_CFLAGS += -I../vendor/hisi/modem/drv/common/src/comm/mailbox
EXTRA_CFLAGS += -I../vendor/hisi/modem/drv/common/src/comm/inc


obj-y += test_hifi.o
