#
# Makefile for thermal drivers.
#
# obj-$(CONFIG_TEMP_SYSFS)	+= tempsys_device.o
# obj-$(CONFIG_THERMAL_NETLINK)	+= thermal_netlink.o
# obj-$(CONFIG_TSENSOR)	    += tsensor_driver.o
# obj-$(CONFIG_TSENSOR)	    += tsensor_governor.o

obj-y	+= tempsys_device.o hkadc_value.o
obj-y	+= thermal_netlink.o
obj-y	    += tsensor_driver.o
obj-y	    += tsensor_governor.o
obj-y	    += hkadc_ctrl.o
obj-y	    += efuse_ctrl.o
obj-y       +=hkadc_debug_device.o
