/******************************************************************************

                  版权所有 (C), 2001-2011, 华为技术有限公司

 ******************************************************************************
 
  This is an AUTO GENERATED file ! DON'T MODIFY MANUAL! 
  文 件 名   : drv_regulator_user.h
  生成日期   : 2014年5月7日
  
******************************************************************************/


#ifndef __DRV_REGULATOR_USER_H__
#define __DRV_REGULATOR_USER_H__

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif
#define ACPU_CORE0_VDD "ACPU_CORE0_VDD"
#define ACPU_CORE0_VDD_USER "ACPU_CORE0_VDD"

#define SCU_VDD "SCU_VDD"
#define SCU_VDD_USER "SCU_VDD"

#define ACPU_L2$_MEMORY_PERIPHERAL_VDD "ACPU_L2$_MEMORY_PERIPHERAL_VDD"
#define ACPU_L2$_MEMORY_PERIPHERAL_VDD_USER "ACPU_L2$_MEMORY_PERIPHERAL_VDD"

#define ACPU_CORE1_VDD "ACPU_CORE1_VDD"
#define ACPU_CORE1_VDD_USER "ACPU_CORE1_VDD"

#define ACPU_CORE2_VDD "ACPU_CORE2_VDD"
#define ACPU_CORE2_VDD_USER "ACPU_CORE2_VDD"

#define ACPU_CORE3_VDD "ACPU_CORE3_VDD"
#define ACPU_CORE3_VDD_USER "ACPU_CORE3_VDD"

#define G3D_VDD "G3D_VDD"
#define G3D_VDD_USER "G3D_VDD"

#define VDDLV_PLL_VDD "VDDLV_PLL_VDD"
#define VDDLV_PLL_VDD_USER "VDDLV_PLL_VDD"

#define DVDD_ABB_VDD "DVDD_ABB_VDD"
#define DVDD_ABB_VDD_USER "DVDD_ABB_VDD"

#define DVDD_USB_VDD "DVDD_USB_VDD"
#define DVDD_USB_VDD_USER "DVDD_USB_VDD"

#define AVCC_MHL_VDD "AVCC_MHL_VDD"
#define AVCC_MHL_VDD_USER "AVCC_MHL_VDD"

#define AVCC_MHLPLL_VDD "AVCC_MHLPLL_VDD"
#define AVCC_MHLPLL_VDD_USER "AVCC_MHLPLL_VDD"

#define PERIPHERAL_VDD_VDD "PERIPHERAL_VDD_VDD"
#define PERIPHERAL_VDD_VDD_USER "PERIPHERAL_VDD_VDD"

#define DSI_PHY_VDD_VDD "DSI_PHY_VDD_VDD"
#define DSI_PHY_VDD_VDD_USER "DSI_PHY_VDD_VDD"

#define CSI_PHY_VDD_VDD "CSI_PHY_VDD_VDD"
#define CSI_PHY_VDD_VDD_USER "CSI_PHY_VDD_VDD"

#define DDR_PHY_VDD_VDD "DDR_PHY_VDD_VDD"
#define DDR_PHY_VDD_VDD_USER "DDR_PHY_VDD_VDD"

#define DDR_PHY_IO_PRE_DRV_VDD "DDR_PHY_IO_PRE_DRV_VDD"
#define DDR_PHY_IO_PRE_DRV_VDD_USER "DDR_PHY_IO_PRE_DRV_VDD"

#define TSENSOR_0P9_VDD "TSENSOR_0P9_VDD"
#define TSENSOR_0P9_VDD_USER "TSENSOR_0P9_VDD"

#define HDMI_PHY_DVDD_VDD "HDMI_PHY_DVDD_VDD"
#define HDMI_PHY_DVDD_VDD_USER "HDMI_PHY_DVDD_VDD"

#define EDC1_VDD "EDC1_VDD"
#define EDC1_VDD_USER "EDC1_VDD"

#define EDC0_VDD "EDC0_VDD"
#define EDC0_VDD_USER "EDC0_VDD"

#define G2D_VDD "G2D_VDD"
#define G2D_VDD_USER "G2D_VDD"

#define ISP_VDD "ISP_VDD"
#define ISP_VDD_USER "ISP_VDD"

#define VDEC_VDD "VDEC_VDD"
#define VDEC_VDD_USER "VDEC_VDD"

#define VPP_VDD "VPP_VDD"
#define VPP_VDD_USER "VPP_VDD"

#define VENC_VDD "VENC_VDD"
#define VENC_VDD_USER "VENC_VDD"

#define HIFI_VDD "HIFI_VDD"
#define HIFI_VDD_USER "HIFI_VDD"

#define BBE16_VDD "BBE16_VDD"
#define BBE16_VDD_USER "BBE16_VDD"

#define CCPU_VDD "CCPU_VDD"
#define CCPU_VDD_USER "CCPU_VDD"

#define TDWBBP1_VDD "TDWBBP1_VDD"
#define TDWBBP1_VDD_USER "TDWBBP1_VDD"

#define TDWBBP2_VDD "TDWBBP2_VDD"
#define TDWBBP2_VDD_USER "TDWBBP2_VDD"

#define GBBP1_VDD "GBBP1_VDD"
#define GBBP1_VDD_USER "GBBP1_VDD"

#define GBBP2_VDD "GBBP2_VDD"
#define GBBP2_VDD_USER "GBBP2_VDD"

#define LTEBBP_VDD "LTEBBP_VDD"
#define LTEBBP_VDD_USER "LTEBBP_VDD"

#define BBPCOMM1_VDD "BBPCOMM1_VDD"
#define BBPCOMM1_VDD_USER "BBPCOMM1_VDD"

#define BBPCOMM2_VDD "BBPCOMM2_VDD"
#define BBPCOMM2_VDD_USER "BBPCOMM2_VDD"

#define ABB_AD_DIG_VDD "ABB_AD_DIG_VDD"
#define ABB_AD_DIG_VDD_USER "ABB_AD_DIG_VDD"

#define ABB_DA_DIG_VDD "ABB_DA_DIG_VDD"
#define ABB_DA_DIG_VDD_USER "ABB_DA_DIG_VDD"

#define VDD_VDD "VDD_VDD"
#define VDD_VDD_USER "VDD_VDD"

#define VDD_DDR_VDD "VDD_DDR_VDD"
#define VDD_DDR_VDD_USER "VDD_DDR_VDD"

#define LPDDR2_VDDCA_VDD "LPDDR2_VDDCA_VDD"
#define LPDDR2_VDDCA_VDD_USER "LPDDR2_VDDCA_VDD"

#define VDDQ_VDD "VDDQ_VDD"
#define VDDQ_VDD_USER "VDDQ_VDD"

#define VDD2_VDD "VDD2_VDD"
#define VDD2_VDD_USER "VDD2_VDD"

#define VDD_P2_VDD "VDD_P2_VDD"
#define VDD_P2_VDD_USER "VDD_P2_VDD"

#define VIN_LDO_L_VDD "VIN_LDO_L_VDD"
#define VIN_LDO_L_VDD_USER "VIN_LDO_L_VDD"

#define DUMMY_VDD "DUMMY_VDD"
#define DUMMY_VDD_USER "DUMMY_VDD"

#define LPDDR2_VDD1_VDD "LPDDR2_VDD1_VDD"
#define LPDDR2_VDD1_VDD_USER "LPDDR2_VDD1_VDD"

#define LPDDR3_VDD1_VDD "LPDDR3_VDD1_VDD"
#define LPDDR3_VDD1_VDD_USER "LPDDR3_VDD1_VDD"

#define VDD_P1_VDD "VDD_P1_VDD"
#define VDD_P1_VDD_USER "VDD_P1_VDD"

#define PMU_IO_VDD "PMU_IO_VDD"
#define PMU_IO_VDD_USER "PMU_IO_VDD"

#define CODEC_IO_VDD "CODEC_IO_VDD"
#define CODEC_IO_VDD_USER "CODEC_IO_VDD"

#define RFIC_DIG_VDD "RFIC_DIG_VDD"
#define RFIC_DIG_VDD_USER "RFIC_DIG_VDD"

#define WIFI_IO_VDD "WIFI_IO_VDD"
#define WIFI_IO_VDD_USER "WIFI_IO_VDD"

#define BT_IO_VDD "BT_IO_VDD"
#define BT_IO_VDD_USER "BT_IO_VDD"

#define GPS_IO_VDD "GPS_IO_VDD"
#define GPS_IO_VDD_USER "GPS_IO_VDD"

#define FM_IO_VDD "FM_IO_VDD"
#define FM_IO_VDD_USER "FM_IO_VDD"

#define SMARTSPKPA_IO_VDD "SMARTSPKPA_IO_VDD"
#define SMARTSPKPA_IO_VDD_USER "SMARTSPKPA_IO_VDD"

#define LVS2_VDD "LVS2_VDD"
#define LVS2_VDD_USER "LVS2_VDD"

#define LVS3_VDD "LVS3_VDD"
#define LVS3_VDD_USER "LVS3_VDD"

#define LVS4_VDD "LVS4_VDD"
#define LVS4_VDD_USER "LVS4_VDD"

#define LVS5_VDD "LVS5_VDD"
#define LVS5_VDD_USER "LVS5_VDD"

#define LVS6_VDD "LVS6_VDD"
#define LVS6_VDD_USER "LVS6_VDD"

#define LVS7_VDD "LVS7_VDD"
#define LVS7_VDD_USER "LVS7_VDD"

#define LVS8_VDD "LVS8_VDD"
#define LVS8_VDD_USER "LVS8_VDD"

#define LVS9_VDD "LVS9_VDD"
#define LVS9_VDD_USER "LVS9_VDD"

#define LVS10_VDD "LVS10_VDD"
#define LVS10_VDD_USER "LVS10_VDD"

#define VIN_LDO_M_VDD "VIN_LDO_M_VDD"
#define VIN_LDO_M_VDD_USER "VIN_LDO_M_VDD"

#define USB_ID_MHL_CBUS_SWITCH_VDD "USB_ID_MHL_CBUS_SWITCH_VDD"
#define USB_ID_MHL_CBUS_SWITCH_VDD_USER "USB_ID_MHL_CBUS_SWITCH_VDD"

#define VIN_LDO_H1_VDD "VIN_LDO_H1_VDD"
#define VIN_LDO_H1_VDD_USER "VIN_LDO_H1_VDD"

#define VIN_LDO_H2_VDD "VIN_LDO_H2_VDD"
#define VIN_LDO_H2_VDD_USER "VIN_LDO_H2_VDD"

#define VIN_LDO_H3_VDD "VIN_LDO_H3_VDD"
#define VIN_LDO_H3_VDD_USER "VIN_LDO_H3_VDD"

#define CLASSD_VDD "CLASSD_VDD"
#define CLASSD_VDD_USER "CLASSD_VDD"

#define HKADC_REF_VDD "HKADC_REF_VDD"
#define HKADC_REF_VDD_USER "HKADC_REF_VDD"

#define TP_ANALOG_VDD "TP_ANALOG_VDD"
#define TP_ANALOG_VDD_USER "TP_ANALOG_VDD"

#define VDD_ON_VDD "VDD_ON_VDD"
#define VDD_ON_VDD_USER "VDD_ON_VDD"

#define DCXO2_VDD "DCXO2_VDD"
#define DCXO2_VDD_USER "DCXO2_VDD"

#define EMMC_VDDM_VDD "EMMC_VDDM_VDD"
#define EMMC_VDDM_VDD_USER "EMMC_VDDM_VDD"

#define DCXO1_VDD "DCXO1_VDD"
#define DCXO1_VDD_USER "DCXO1_VDD"

#define VDDH_SDIO_VDD "VDDH_SDIO_VDD"
#define VDDH_SDIO_VDD_USER "VDDH_SDIO_VDD"

#define AVDD13_ABB_VDD "AVDD13_ABB_VDD"
#define AVDD13_ABB_VDD_USER "AVDD13_ABB_VDD"

#define SIM1_VDD "SIM1_VDD"
#define SIM1_VDD_USER "SIM1_VDD"

#define SD_CARD_VDD "SD_CARD_VDD"
#define SD_CARD_VDD_USER "SD_CARD_VDD"

#define SIM2_VDD "SIM2_VDD"
#define SIM2_VDD_USER "SIM2_VDD"

#define VDD33_USB_VDD "VDD33_USB_VDD"
#define VDD33_USB_VDD_USER "VDD33_USB_VDD"

#define MHL_SWITCH_VDD "MHL_SWITCH_VDD"
#define MHL_SWITCH_VDD_USER "MHL_SWITCH_VDD"

#define SENSORS_ANALOG_VDD "SENSORS_ANALOG_VDD"
#define SENSORS_ANALOG_VDD_USER "SENSORS_ANALOG_VDD"

#define S_BACKUP_CAMERA_CORE_VDD "S_BACKUP_CAMERA_CORE_VDD"
#define S_BACKUP_CAMERA_CORE_VDD_USER "S_BACKUP_CAMERA_CORE_VDD"

#define M_CAMERA_ANALOG_VDD "M_CAMERA_ANALOG_VDD"
#define M_CAMERA_ANALOG_VDD_USER "M_CAMERA_ANALOG_VDD"

#define M_CAMERA_VCM_VDD "M_CAMERA_VCM_VDD"
#define M_CAMERA_VCM_VDD_USER "M_CAMERA_VCM_VDD"

#define M_CAMERA_CORE_VDD "M_CAMERA_CORE_VDD"
#define M_CAMERA_CORE_VDD_USER "M_CAMERA_CORE_VDD"

#define S_CAMERA_ANALOG_VDD "S_CAMERA_ANALOG_VDD"
#define S_CAMERA_ANALOG_VDD_USER "S_CAMERA_ANALOG_VDD"

#define VDD_APMEM_VDD "VDD_APMEM_VDD"
#define VDD_APMEM_VDD_USER "VDD_APMEM_VDD"

#define VIBRATOR_VDD "VIBRATOR_VDD"
#define VIBRATOR_VDD_USER "VIBRATOR_VDD"

#define S_CAMERA_CORE_FOR_BACKUP2_VDD "S_CAMERA_CORE_FOR_BACKUP2_VDD"
#define S_CAMERA_CORE_FOR_BACKUP2_VDD_USER "S_CAMERA_CORE_FOR_BACKUP2_VDD"

#define VDDL_SDIO_VDD "VDDL_SDIO_VDD"
#define VDDL_SDIO_VDD_USER "VDDL_SDIO_VDD"

#define VDDSYS_EFUSE_VDD "VDDSYS_EFUSE_VDD"
#define VDDSYS_EFUSE_VDD_USER "VDDSYS_EFUSE_VDD"

#define PMU_AUXDAC_VDD "PMU_AUXDAC_VDD"
#define PMU_AUXDAC_VDD_USER "PMU_AUXDAC_VDD"

#define CODEC_AVDD_VDD "CODEC_AVDD_VDD"
#define CODEC_AVDD_VDD_USER "CODEC_AVDD_VDD"

#define TP_IO_VDD "TP_IO_VDD"
#define TP_IO_VDD_USER "TP_IO_VDD"

#define S_CAMERA_IO_VDD "S_CAMERA_IO_VDD"
#define S_CAMERA_IO_VDD_USER "S_CAMERA_IO_VDD"

#define M_CAMERA_IO_VDD "M_CAMERA_IO_VDD"
#define M_CAMERA_IO_VDD_USER "M_CAMERA_IO_VDD"

#define LCD_IO_VDD "LCD_IO_VDD"
#define LCD_IO_VDD_USER "LCD_IO_VDD"

#define PA_STAR_VDD_VDD "PA_STAR_VDD_VDD"
#define PA_STAR_VDD_VDD_USER "PA_STAR_VDD_VDD"

#define EMMC_VDDQ_VDD "EMMC_VDDQ_VDD"
#define EMMC_VDDQ_VDD_USER "EMMC_VDDQ_VDD"

#define AUDIO_CODEC_ANALOG_1P8V_VDD "AUDIO_CODEC_ANALOG_1P8V_VDD"
#define AUDIO_CODEC_ANALOG_1P8V_VDD_USER "AUDIO_CODEC_ANALOG_1P8V_VDD"

#define SENSOR_IO_VDD "SENSOR_IO_VDD"
#define SENSOR_IO_VDD_USER "SENSOR_IO_VDD"

#define NFC_IO_VDD "NFC_IO_VDD"
#define NFC_IO_VDD_USER "NFC_IO_VDD"

#define AVDD_MIPI_DSI_VDD "AVDD_MIPI_DSI_VDD"
#define AVDD_MIPI_DSI_VDD_USER "AVDD_MIPI_DSI_VDD"

#define AVDD_MIPI_CSI_VDD "AVDD_MIPI_CSI_VDD"
#define AVDD_MIPI_CSI_VDD_USER "AVDD_MIPI_CSI_VDD"

#define AVDD18_ABB_VDD "AVDD18_ABB_VDD"
#define AVDD18_ABB_VDD_USER "AVDD18_ABB_VDD"

#define VDDHV_PLL_VDD "VDDHV_PLL_VDD"
#define VDDHV_PLL_VDD_USER "VDDHV_PLL_VDD"

#define VDD18_MHL_VDD "VDD18_MHL_VDD"
#define VDD18_MHL_VDD_USER "VDD18_MHL_VDD"

#define VDD18_USB_VDD "VDD18_USB_VDD"
#define VDD18_USB_VDD_USER "VDD18_USB_VDD"

#define VDD_DDRPLL0_VDD "VDD_DDRPLL0_VDD"
#define VDD_DDRPLL0_VDD_USER "VDD_DDRPLL0_VDD"

#define VDD_DDRPLL1_VDD "VDD_DDRPLL1_VDD"
#define VDD_DDRPLL1_VDD_USER "VDD_DDRPLL1_VDD"

#define VDD_DDRPLL2_VDD "VDD_DDRPLL2_VDD"
#define VDD_DDRPLL2_VDD_USER "VDD_DDRPLL2_VDD"

#define AVDD_TS_VDD "AVDD_TS_VDD"
#define AVDD_TS_VDD_USER "AVDD_TS_VDD"

#define VDDM_SDIO_VDD "VDDM_SDIO_VDD"
#define VDDM_SDIO_VDD_USER "VDDM_SDIO_VDD"

#define S_CAMERA_CORE_VDD "S_CAMERA_CORE_VDD"
#define S_CAMERA_CORE_VDD_USER "S_CAMERA_CORE_VDD"

#define RF1602_EN_VDD "RF1602_EN_VDD"
#define RF1602_EN_VDD_USER "RF1602_EN_VDD"

#define FLASH_MASK_IO_VDD "FLASH_MASK_IO_VDD"
#define FLASH_MASK_IO_VDD_USER "FLASH_MASK_IO_VDD"

#define S_CAMERA_CORE_FOR_BACKUP1_VDD "S_CAMERA_CORE_FOR_BACKUP1_VDD"
#define S_CAMERA_CORE_FOR_BACKUP1_VDD_USER "S_CAMERA_CORE_FOR_BACKUP1_VDD"

#define SIM2_RESERVED_VDD "SIM2_RESERVED_VDD"
#define SIM2_RESERVED_VDD_USER "SIM2_RESERVED_VDD"

#define MINI_ISP_ANALOG_VDD "MINI_ISP_ANALOG_VDD"
#define MINI_ISP_ANALOG_VDD_USER "MINI_ISP_ANALOG_VDD"

#define M_CAMERA_IO_RESERVE_VDD "M_CAMERA_IO_RESERVE_VDD"
#define M_CAMERA_IO_RESERVE_VDD_USER "M_CAMERA_IO_RESERVE_VDD"

#define LCD_IO_RESERVED_VDD "LCD_IO_RESERVED_VDD"
#define LCD_IO_RESERVED_VDD_USER "LCD_IO_RESERVED_VDD"



#ifdef __cplusplus
    #if __cplusplus
        }
    #endif
#endif

#endif
