##############################################

EXTRA_CFLAGS += -Idrivers/huawei/drivers/camera/miniisp/camera/sonyimx179
EXTRA_CFLAGS += -Idrivers/huawei/drivers/camera/miniISP/camera
obj-y += sonyimx179.o

#################### END #####################
