EXTRA_CFLAGS += -Idrivers/mailbox/
EXTRA_CFLAGS += -I../vendor/hisi/include/drv/MODULE_H
EXTRA_CFLAGS += -I../vendor/hisi/modem/drv/common/src/comm/mailbox
EXTRA_CFLAGS += -I../vendor/hisi/modem/drv/hi6620/src/comm/inc

obj-y += drv_mailbox_test_linux.o
