EXTRA_CFLAGS   += -Idrivers/mntn
EXTRA_CFLAGS   += -Idrivers/hisi/test/mailbox
EXTRA_CFLAGS += -I../vendor/hisi/modem/drv/hi6620/src/comm/inc
EXTRA_CFLAGS += -I../vendor/hisi/modem/drv/common/src/comm/mailbox



obj-y          += drv_mailbox_table.o
obj-y          += drv_mailbox_gut.o
obj-y          += drv_mailbox_ifc.o
obj-y          += drv_mailbox_msg.o
obj-y          += drv_mailbox_debug.o
obj-y          += drv_mailbox_port_linux.o
obj-y	       += drv_mailbox_ifc.o
obj-y	       += drv_mailbox.o

