EXTRA_CFLAGS += -Idrivers/huawei/drivers/camera/flash/
EXTRA_CFLAGS += -fno-pic 
obj-y += torchclass.o 
obj-$(CONFIG_HI6620_CAMERA_FLASH_LM3642) += lm3642.o 
obj-$(CONFIG_HI6620_CAMERA_FLASH_TPS61310) += tps61310.o 
#obj-m += k3_flash.o 
