
#EXTRA_CFLAGS   			+= -Idrivers/multicore/udi/
EXTRA_CFLAGS   			+= -Idrivers/multicore/ipcm/
#EXTRA_CFLAGS   			+= -Idrivers/mntn/include/
EXTRA_CFLAGS   			+= -Idrivers/mntn

obj-y		+= bsp_icc.o
obj-y		+= icc_test.o
