#sensor unification for differ platform
obj-$(CONFIG_HUAWEI_SENSORS_INPUT_INFO)	+= sensor_info.o
obj-y	+= gyroscope/
obj-y	+= light/
obj-y	+= accelerometer/
obj-y	+= compass/
obj-y   += captouch/
obj-y	+= hall/

