##############################################
#     Make file of SONYIMX135 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/huawei/drivers/camera/sonyimx135/
#EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HI6620_CAMERA_SONYIMX135) += sonyimx135.o
obj-y += sonyimx135.o
#################### END #####################
