##############################################
#     Make file of SONYIMX105 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/huawei/drivers/camera/sonyimx134/
#EXTRA_CFLAGS += -fno-pic 
ccflags-$(CONFIG_HI6620_CAMERA_SONYIMX134) += -DIMX134_OTP
obj-$(CONFIG_HI6620_CAMERA_SONYIMX134) += sonyimx134.o

#################### END #####################
