
EXTRA_CFLAGS += -fno-pic
obj-$(CONFIG_MEDIA_VIDEO_MNTN) += media_mntn_kernel.o

obj-y += mntn_log_debugfs.o \
         video_mntn_kernel.o
obj-m += media_mntn_sys_crash.o                                                            