##############################################
#     Make file of SONYIMX179 camera sensor
##############################################

ccflags-$(CONFIG_HI6620_CAMERA_SONYIMX179) += -DIMX179_OTP
EXTRA_CFLAGS += -Idrivers/huawei/drivers/camera/sonyimx179/
obj-$(CONFIG_HI6620_CAMERA_SONYIMX179) += sonyimx179.o

#################### END #####################
