EXTRA_CFLAGS += -I../vendor/hisi/modem/drv/hi6620/src/comm/inc

obj-y      	+= multi_core.o
obj-y		+= icc/
#obj-y		+= ifc/
#obj-y		+= udi/
obj-y		+= ipcm/
obj-y		+= common/
#obj-$(CONFIG_BALONG_MULTICORE_TEST)           += test/
