EXTRA_CFLAGS                    += -Idrivers/usb/gadget/
EXTRA_CFLAGS                    += -Idrivers/usb/susb/

obj-y				+= usb_shell.o
obj-y				+= drv_if_usb.o
obj-y				+= acm_ldisc.o
obj-y				+= acm_ncopy_io.o
#obj-y				+= test_acm.o
