#
# Makefile for huawei camera sensors
#

obj-$(CONFIG_HI6620_CAMERA_FLASH) += flash/

subdir-ccflags-y += -Idrivers/media/video/hi6620/capture/isp/
subdir-ccflags-y += -Idrivers/media/video/hi6620/capture/isp_for_misp/
subdir-ccflags-y += -Idrivers/media/video/hi6620/capture/common/
obj-y += mini_isp/





obj-$(CONFIG_HI6620_CAMERA_S5K4E1GA_FOXCONN) += s5k4e1ga_foxconn/
obj-$(CONFIG_HI6620_CAMERA_SONYIMX134) += sonyimx134/
obj-$(CONFIG_HI6620_CAMERA_SONYIMX135) += sonyimx135/
obj-$(CONFIG_HI6620_CAMERA_SONYIMX214) += sonyimx214/
obj-$(CONFIG_HI6620_CAMERA_OV5648_FOXCONN) += ov5648_foxconn/
obj-$(CONFIG_HI6620_CAMERA_OV5648_SUNNY) += ov5648_sunny/
obj-$(CONFIG_HI6620_CAMERA_S5K4E1GX_FOXCONN) += s5k4e1gx_foxconn/
obj-$(CONFIG_HI6620_CAMERA_SONYIMX179) += sonyimx179/





